_wandb:
    value:
        cli_version: 0.26.1
        e:
            f9tnz9d9aeyj31jilf6oqgdpp7z7gq0h:
                codePath: parameter_search.py
                codePathLocal: parameter_search.py
                cpu_count: 52
                cpu_count_logical: 52
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "101237272576"
                        used: "7545053184"
                email: ramakrishna1106s@gmail.com
                executable: /gpfs/home/cqp0132/vae_sweep_project/vae_env/bin/python
                gpu: NVIDIA A100-PCIE-40GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-PCIE-40GB
                      uuid: GPU-be3d1642-11b0-a99d-d918-b7d040238284
                host: qgpu0403
                memory:
                    total: "202474549248"
                os: Linux-4.18.0-553.64.1.el8_10.x86_64-x86_64-with-glibc2.28
                program: /gpfs/home/cqp0132/vae_sweep_project/parameter_search.py
                python: CPython 3.10.20
                root: /gpfs/home/cqp0132/vae_sweep_project
                slurm:
                    cluster_name: quest
                    conf: /etc/slurm/slurm.conf
                    cpus_on_node: "4"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: e32706
                    job_cpus_per_node: "4"
                    job_end_time: "1777889596"
                    job_gid: "11010591"
                    job_gpus: "0"
                    job_id: "7119050"
                    job_name: vae_hyperband
                    job_nodelist: qgpu0403
                    job_num_nodes: "1"
                    job_partition: gengpu
                    job_qos: normal
                    job_start_time: "1777875196"
                    job_uid: "11010591"
                    job_user: cqp0132
                    jobid: "7119050"
                    localid: "0"
                    mem_per_node: "20480"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: qgpu0403
                    nprocs: "4"
                    ntasks: "4"
                    ntasks_per_node: "4"
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    submit_dir: /gpfs/home/cqp0132/vae_sweep_project
                    submit_host: quser42
                    task_pid: "1071910"
                    tasks_per_node: "4"
                    topology_addr: qgpu0403
                    topology_addr_pattern: node
                startedAt: "2026-05-04T06:16:06.482150Z"
                writerId: f9tnz9d9aeyj31jilf6oqgdpp7z7gq0h
        m: []
        python_version: 3.10.20
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 2
                - 14
            "4": 3.10.20
            "5": 0.26.1
            "12": 0.26.1
            "13": linux-x86_64
beta:
    value: 0.5
epochs:
    value: 15
latent_dim:
    value: 32
learning_rate:
    value: 0.001
